### ISSUE TITLE
fm file generation error for FM4 test case

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#155]
policytc file

layer_id | level_id | agg_id | policytc_id
-- | -- | -- | --
1 | 1 | 1 | 1
1 | 1 | 2 | 1
1 | 1 | 3 | 1
1 | 1 | 4 | 2
1 | 2 | 1 | 3
1 | 2 | 2 | 3*
1 | 3 | 1 | 4

*policytc_id should be 1 not 3. A pass through rule should be applied to the time element (cov 4) at level 2, because it has already had the financial term applied at level 1. policytc_id 3 is the financial terms for physical damage (cov 5).

**Comment by sr-murthy** [comment]
Fixed - the policy TC file for FM4 (generated via the loss script and the FM acceptance test case) is now

    layer_id,level_id,agg_id,policytc_id
    1,1,1,1
    1,1,2,1
    1,1,3,1
    1,1,4,2
    1,2,1,3
    1,2,2,3
    1,3,1,4

The profile file is the same as before

    policytc_id,calcrule_id,deductible1,deductible2,deductible3,attachment1,limit1,share1,share2,share3
    1,12,0.0,0.0,0.0,0.0,0.0,0.0,0,0
    2,1,2000.0,0.0,0.0,0.0,18000.0,0.0,0,0
    3,1,1000.0,0.0,0.0,0.0,1000000.0,0.0,0,0
    4,2,0.0,0.0,0.0,0.0,9999999999.0,1.0,0,0

**Comment by johcarter** [comment]
policytc file is not fixed (tested in ReinsuranceTestTool dev branch using run_direct.ipynb. 
Issue is described above

**Comment by sr-murthy** [comment]
@johcarter This was fixed in the MDK. I know because we saw the FM4 acceptance test passing - in those acceptance tests source OED files which have only the required columns are auto-generated.

 I have compared the account file generated in the FM4 acceptance test case with the one you’re using for FM3 in the RTT repository and it appears there are two differences: `PolMinDed6All` is 0 in yours but null in mine and `CondNumber` is 1 in mine but null in yours. I’ll have to check but this might explain the discrepancy.

**Comment by sr-murthy** [comment]
@johcarter I've finally figured out why the discrepancy exists in the policy TC ID file in your notebook run of FM3 - the level 2 financial terms in the MDK default can. loc. profile are all missing the `CoverageTypeID` field, as this is how the pass through rule for level 2 BI coverages is implemented. So the level 2 limit in the loc. profile should look like this

        "LocLimit5PD": {
            "ProfileElementName": "LocLimit5PD",
            "FieldName": "SitePDLimit",
            "FMLevelName": "SitePD",
            "FMLevel": 2,
            "FMTermType": "Limit",
            "FMTermGroupID": 1,
            "CoverageTypeID": [1,2,3],
            "ProfileType": "Loc"
    }

but instead it is missing that `CoverageTypeID` key. The FM level terms generators implement these coverage-type based rules using that `CoverageTypeID` key. If that's missing the term is extracted from the corresponding source file, otherwise it attempts to match the range of acceptable coverage type IDs from the profile term for that level term to the coverage type of the FM item being processed at that level.

Same here for the level 2 deductible `LocDed5PD`.

So it's just a matter of updating the profile, which I have done, and no changes to the FM code were required, because it is profile driven. You can try to run FM3 again tomorrow.

**Comment by sr-murthy** [comment]
@johcarter I have verified that the policy TC file for FM4 has the correct policy TC ID for level 2 items. Please see the screenshot below

![screen shot 2019-02-15 at 13 52 52](https://user-images.githubusercontent.com/9358070/52861208-ae590300-3129-11e9-9e02-b2de522cf47d.png)

I have run losses as well, and the numbers look identical to what they are with the corresponding FM4 acceptance test produces.

![screen shot 2019-02-15 at 13 58 17](https://user-images.githubusercontent.com/9358070/52861274-e82a0980-3129-11e9-92a2-d5da6f14a803.png)

I have run both FM3 and FM4, including loss generation, and it looks fine.

As I said there was no error in the MDK - one of the static loc. profile terms was missing a key, because the MDK was caching an older file, which I've deleted.
